// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {commands} from '../models';
import {domain} from '../models';
import {bridge} from '../models';

export function AddProviderKeys(arg1:string,arg2:Array<string>):Promise<Array<main.AuthProvider>>;

export function DeleteSession(arg1:string):Promise<void>;

export function EmitError(arg1:Error):Promise<void>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function ExecuteRickCommand(arg1:string,arg2:boolean):Promise<commands.Result>;

export function ExportSession(arg1:string):Promise<string>;

export function ExportSettings():Promise<string>;

export function ForkSession(arg1:string):Promise<main.Session>;

export function GetAuthStatus():Promise<Array<main.AuthProvider>>;

export function GetCommandCatalog():Promise<Array<domain.CommandSpec>>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetDefaultModel():Promise<string>;

export function GetMCPStatus():Promise<Array<Record<string, any>>>;

export function GetProviders():Promise<Array<main.Provider>>;

export function GetResolvedConfig(arg1:string):Promise<Record<string, any>>;

export function GetRickStatus():Promise<main.RickStatus>;

export function GetRickVersion():Promise<string>;

export function GetRuntimeInfo():Promise<main.RuntimeInfo>;

export function GetSessionMessages(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetTools():Promise<Array<bridge.ToolInfo>>;

export function GetUpdateStatus():Promise<main.UpdateInfo>;

export function GetUsageDaily(arg1:number):Promise<Array<main.DailyUsage>>;

export function GetUsageStats(arg1:string,arg2:string):Promise<main.UsageStats>;

export function ImportSession(arg1:string,arg2:string):Promise<main.Session>;

export function ImportSettings(arg1:string):Promise<void>;

export function InstallRick():Promise<main.RickStatus>;

export function InstallUpdate():Promise<void>;

export function KillAgent(arg1:string,arg2:string):Promise<void>;

export function ListAgents(arg1:string):Promise<void>;

export function PickBackgroundFile(arg1:string):Promise<string>;

export function PickFolder():Promise<string>;

export function RemoveProvider(arg1:string):Promise<Array<main.AuthProvider>>;

export function RemoveProviderKey(arg1:string,arg2:number):Promise<Array<main.AuthProvider>>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RequestCompact(arg1:string):Promise<Record<string, any>>;

export function RequestGoals(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:Array<string>):Promise<Record<string, any>>;

export function RequestPlugins(arg1:string,arg2:string,arg3:string,arg4:any):Promise<any>;

export function RequestSnapshot(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ResetSettings():Promise<void>;

export function RespondPermission(arg1:string,arg2:string):Promise<void>;

export function RunPrompt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunPromptWithOptions(arg1:string,arg2:string,arg3:string,arg4:main.RunOptions):Promise<string>;

export function SaveProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.AuthProvider>>;

export function SearchSessions(arg1:string):Promise<Array<main.Session>>;

export function SetSessionCategory(arg1:string,arg2:string):Promise<void>;

export function SetSessionFavorite(arg1:string,arg2:boolean):Promise<void>;

export function SteerAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StopRun(arg1:string):Promise<void>;

export function UpdateConfig(arg1:main.DesktopConfig):Promise<void>;

export function UpdateProvider(arg1:string,arg2:any,arg3:any,arg4:string,arg5:string,arg6:string,arg7:string):Promise<Array<main.AuthProvider>>;

export function UpdateRickConfig(arg1:Record<string, any>):Promise<Record<string, any>>;
