// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProviderKeys(arg1, arg2) {
  return window['go']['main']['App']['AddProviderKeys'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function EmitError(arg1) {
  return window['go']['main']['App']['EmitError'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function ExecuteRickCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRickCommand'](arg1, arg2);
}

export function ExportSession(arg1) {
  return window['go']['main']['App']['ExportSession'](arg1);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function ForkSession(arg1) {
  return window['go']['main']['App']['ForkSession'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetCommandCatalog() {
  return window['go']['main']['App']['GetCommandCatalog']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultModel() {
  return window['go']['main']['App']['GetDefaultModel']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetResolvedConfig(arg1) {
  return window['go']['main']['App']['GetResolvedConfig'](arg1);
}

export function GetRickStatus() {
  return window['go']['main']['App']['GetRickStatus']();
}

export function GetRickVersion() {
  return window['go']['main']['App']['GetRickVersion']();
}

export function GetRuntimeInfo() {
  return window['go']['main']['App']['GetRuntimeInfo']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function GetUsageDaily(arg1) {
  return window['go']['main']['App']['GetUsageDaily'](arg1);
}

export function GetUsageStats(arg1, arg2) {
  return window['go']['main']['App']['GetUsageStats'](arg1, arg2);
}

export function ImportSession(arg1, arg2) {
  return window['go']['main']['App']['ImportSession'](arg1, arg2);
}

export function ImportSettings(arg1) {
  return window['go']['main']['App']['ImportSettings'](arg1);
}

export function InstallRick() {
  return window['go']['main']['App']['InstallRick']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function KillAgent(arg1, arg2) {
  return window['go']['main']['App']['KillAgent'](arg1, arg2);
}

export function ListAgents(arg1) {
  return window['go']['main']['App']['ListAgents'](arg1);
}

export function PickBackgroundFile() {
  return window['go']['main']['App']['PickBackgroundFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RemoveProviderKey(arg1, arg2) {
  return window['go']['main']['App']['RemoveProviderKey'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RequestCompact(arg1) {
  return window['go']['main']['App']['RequestCompact'](arg1);
}

export function RequestGoals(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RequestGoals'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RequestPlugins(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RequestPlugins'](arg1, arg2, arg3, arg4);
}

export function RequestSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestSnapshot'](arg1, arg2, arg3);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function RunPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunPrompt'](arg1, arg2, arg3);
}

export function RunPromptWithOptions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunPromptWithOptions'](arg1, arg2, arg3, arg4);
}

export function SaveProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveProvider'](arg1, arg2, arg3, arg4);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SetSessionCategory(arg1, arg2) {
  return window['go']['main']['App']['SetSessionCategory'](arg1, arg2);
}

export function SetSessionFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetSessionFavorite'](arg1, arg2);
}

export function SteerAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SteerAgent'](arg1, arg2, arg3, arg4);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateRickConfig(arg1) {
  return window['go']['main']['App']['UpdateRickConfig'](arg1);
}
